graphhopper:
  osmFile: "src/main/resources/static/ukraine-latest.osm.pbf"
  graphFolder: "path/to/graph-cache"
  graphURL: "https://graphhopper.com/api/1/vrp?key=api_key"

server:
  port: 8080



spring:
  neo4j:
    uri: "bolt://my-server:7474"
    authentication:
      username: "neo4j"
      password: "secret"


